const CTP_EBAY_CAMPAIGN = '5339172120';
const ebaySearch = (query, customId) => `https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(query)}&mkcid=1&mkrid=711-53200-19255-0&siteid=0&campid=${CTP_EBAY_CAMPAIGN}&customid=${encodeURIComponent(customId)}&toolid=10001&mkevt=1`;

window.CTP_PRODUCTS = [
  {id:'tools-1',category:'tools',icon:'🧰',name:'DEWALT 20V MAX Tool Kits',reason:'A practical starting point for remodelers, homeowners and contractors who want one battery platform for everyday work.',retailer:'eBay',status:'Shop current eBay listings',used:false,url:ebaySearch('DEWALT 20V MAX tool kit','ctp-dewalt-kits')},
  {id:'tools-2',category:'tools',icon:'🔩',name:'Impact Drivers & Drill Drivers',reason:'Core jobsite tools for deck screws, structural fasteners, drilling and general repair work.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('DEWALT 20V impact driver drill driver','ctp-impact-drill')},
  {id:'tools-3',category:'tools',icon:'📏',name:'Contractor Measuring & Layout Tools',reason:'Tape measures, speed squares, levels and layout gear that belong in every serious tool setup.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('contractor tape measure speed square level','ctp-layout')},
  {id:'tools-4',category:'tools',icon:'🪚',name:'Circular Saws & Reciprocating Saws',reason:'Useful for framing, decking, demolition, remodeling and repair work where dependable cutting power matters.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('DEWALT 20V circular saw reciprocating saw','ctp-saws')},
  {id:'tools-5',category:'tools',icon:'📐',name:'Laser Levels & Distance Measures',reason:'Faster layout for cabinets, trim, decks, framing and estimates when repeatable level and distance readings matter.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('contractor laser level distance measure','ctp-laser-layout')},
  {id:'tools-6',category:'tools',icon:'🔨',name:'Cordless Framing & Finish Nailers',reason:'Useful for framing, trim and punch-list work without dragging a compressor and hose through occupied homes.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('cordless framing nailer finish nailer','ctp-cordless-nailers')},
  {id:'tools-7',category:'tools',icon:'🛠️',name:'Oscillating Multi-Tools & Blades',reason:'One of the most useful remodeling tools for plunge cuts, trim removal, drywall, flooring and tight-access repairs.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('oscillating multi tool blade set contractor','ctp-multi-tools')},
  {id:'tools-8',category:'tools',icon:'🧹',name:'Jobsite Vacuums & Dust Control',reason:'Helps control cleanup time and airborne dust during remodeling, sanding, cutting and occupied-home work.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('jobsite vacuum dust extractor HEPA contractor','ctp-dust-control')},

  {id:'welding-1',category:'welding',icon:'🥽',name:'Welding Helmets & PPE',reason:'Welding helmets, gloves, jackets and protective gear for fabrication and repair work.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('welding helmet gloves PPE','ctp-welding-ppe')},
  {id:'welding-2',category:'welding',icon:'⚡',name:'Welding & Fabrication Tools',reason:'Clamps, magnets, grinders, inspection tools and shop gear useful around welding and fabrication work.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('welding fabrication tools clamps magnets grinder','ctp-welding-tools')},
  {id:'welding-3',category:'welding',icon:'🔥',name:'MIG, TIG & Multi-Process Welders',reason:'Compare portable and shop machines by process, input power, duty cycle and the work they are realistically built to handle.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('MIG TIG multi process welder 120V 240V','ctp-welding-machines')},
  {id:'welding-4',category:'welding',icon:'✨',name:'Plasma Cutters & Consumables',reason:'Useful for fabrication and repair work when clean material separation is faster than abrasive cutting.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('plasma cutter consumables 120V 240V','ctp-plasma-cutters')},
  {id:'welding-5',category:'welding',icon:'🧲',name:'Welding Tables, Clamps & Magnets',reason:'Better fit-up and restraint make fabrication faster and help reduce movement, distortion and rework.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('welding table clamps magnets fabrication fixture','ctp-welding-fitup')},
  {id:'welding-6',category:'welding',icon:'🔍',name:'Weld Inspection & Measurement Tools',reason:'Fillet gauges, bridge-cam gauges, mirrors, lights and measurement tools for fabrication quality checks.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('weld inspection gauge bridge cam fillet gauge','ctp-weld-inspection')},

  {id:'garage-1',category:'garage',icon:'🏍️',name:'Harley-Davidson Garage & Maintenance Gear',reason:'Maintenance tools, accessories, storage and garage items for Harley owners and riders.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('Harley Davidson maintenance tools garage accessories','ctp-harley')},
  {id:'garage-2',category:'garage',icon:'🔧',name:'Mechanic Hand Tool Sets',reason:'Sockets, ratchets, wrenches and mechanic tools for vehicle, motorcycle and garage repair work.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('mechanic tool set sockets ratchets wrenches','ctp-mechanic-tools')},
  {id:'garage-3',category:'garage',icon:'🔋',name:'Battery Chargers & Jump Packs',reason:'Portable starting power and battery maintenance can prevent downtime when trucks, cars, bikes and equipment sit.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('automotive battery charger maintainer jump pack','ctp-battery-power')},
  {id:'garage-4',category:'garage',icon:'🛞',name:'TPMS, Scan & Diagnostic Tools',reason:'Basic vehicle data can turn warning lights and limp-mode symptoms into a focused repair path instead of guesswork.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('OBD2 scanner TPMS diagnostic tool','ctp-vehicle-diagnostics')},
  {id:'garage-5',category:'garage',icon:'🏗️',name:'Motorcycle Lifts, Jacks & Stands',reason:'Stable access matters for safe motorcycle maintenance, tire work, cleaning and winter storage.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('motorcycle lift jack stand Harley','ctp-motorcycle-lifts')},

  {id:'cards-1',category:'cards',icon:'🃏',name:'Trading Card Protection & Grading Prep',reason:'Penny sleeves, semi-rigid holders, top loaders and storage supplies for protecting cards and preparing submissions.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('trading card penny sleeves semi rigid top loaders grading','ctp-card-protection')},
  {id:'cards-2',category:'cards',icon:'📦',name:'Card Storage & Sorting Supplies',reason:'Storage boxes, dividers, binders and sorting supplies for larger sports and trading-card collections.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('trading card storage box dividers binder','ctp-card-storage')},
  {id:'cards-3',category:'cards',icon:'🔎',name:'Card Magnifiers, Lights & Centering Tools',reason:'Simple inspection tools help identify surface, edge, corner and centering issues before grading or listing.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('trading card magnifier light centering tool grading','ctp-card-inspection')},
  {id:'cards-4',category:'cards',icon:'🧱',name:'Slab Storage & Display Cases',reason:'Protect graded cards while keeping higher-value pieces organized, portable and presentable.',retailer:'eBay',status:'Shop current eBay listings',used:true,url:ebaySearch('graded card slab storage case display','ctp-slab-storage')},

  {id:'deals-1',category:'deals',icon:'🔥',name:'eBay Tool Deals',reason:'Search current eBay listings for tool deals, open-box items and value buys across major brands.',retailer:'eBay',status:'Browse current deals',used:false,url:ebaySearch('power tools deals open box','ctp-tool-deals')},
  {id:'deals-2',category:'deals',icon:'💰',name:'eBay Home Improvement Deals',reason:'Current listings for home repair, hardware, lawn and garden equipment at a range of price points.',retailer:'eBay',status:'Browse current deals',used:false,url:ebaySearch('home improvement tools lawn garden deals','ctp-home-deals')},
  {id:'deals-3',category:'deals',icon:'📦',name:'Open-Box & Certified Refurbished Tools',reason:'A practical search for lower-cost equipment where condition, seller history, warranty and return terms can be compared.',retailer:'eBay',status:'Browse current deals',used:false,url:ebaySearch('certified refurbished open box power tools','ctp-refurb-tools')}
];