const CTP_EBAY_CAMPAIGN='5339172120';
const ebaySearch=(query,customId)=>`https://www.ebay.com/sch/i.html?_nkw=${encodeURIComponent(query)}&mkcid=1&mkrid=711-53200-19255-0&siteid=0&campid=${CTP_EBAY_CAMPAIGN}&customid=${encodeURIComponent(customId)}&toolid=10001&mkevt=1`;
const P=(id,category,name,reason,status,used,query,customId,visualTitle,visualMeta,features)=>({id,category,name,reason,retailer:'eBay',status,used,url:ebaySearch(query,customId),visualTitle,visualMeta,features});
window.CTP_PRODUCTS=[
P('tools-1','tools','DEWALT 20V MAX Tool Kits','A practical starting point for remodelers, homeowners and contractors who want one battery platform for everyday work.','Shop current eBay listings',false,'DEWALT 20V MAX tool kit','ctp-dewalt-kits','20V MAX SYSTEM','KITS • BATTERIES • JOBSITE',['Battery platform','Kit value','Daily use']),
P('tools-2','tools','Impact Drivers & Drill Drivers','Core jobsite tools for deck screws, structural fasteners, drilling and general repair work.','Shop current eBay listings',true,'DEWALT 20V impact driver drill driver','ctp-impact-drill','DRIVE POWER','IMPACT • DRILL • FASTEN',['Fastening','Drilling','Deck work']),
P('tools-3','tools','Contractor Measuring & Layout Tools','Tape measures, speed squares, levels and layout gear that belong in every serious tool setup.','Shop current eBay listings',true,'contractor tape measure speed square level','ctp-layout','LAYOUT SYSTEM','MEASURE • SQUARE • LEVEL',['Accuracy','Layout','Everyday carry']),
P('tools-4','tools','Circular Saws & Reciprocating Saws','Useful for framing, decking, demolition, remodeling and repair work where dependable cutting power matters.','Shop current eBay listings',true,'DEWALT 20V circular saw reciprocating saw','ctp-saws','CUTTING POWER','FRAME • DEMO • REMODEL',['Framing','Demolition','Cordless']),
P('tools-5','tools','Laser Levels & Distance Measures','Faster layout for cabinets, trim, decks, framing and estimates when repeatable level and distance readings matter.','Shop current eBay listings',true,'contractor laser level distance measure','ctp-laser-layout','PRECISION LAYOUT','LASER • DISTANCE • LEVEL',['Estimating','Layout','Precision']),
P('tools-6','tools','Cordless Framing & Finish Nailers','Useful for framing, trim and punch-list work without dragging a compressor and hose through occupied homes.','Shop current eBay listings',true,'cordless framing nailer finish nailer','ctp-cordless-nailers','CORDLESS NAILING','FRAME • TRIM • PUNCH',['No compressor','Trim','Framing']),
P('tools-7','tools','Oscillating Multi-Tools & Blades','One of the most useful remodeling tools for plunge cuts, trim removal, drywall, flooring and tight-access repairs.','Shop current eBay listings',true,'oscillating multi tool blade set contractor','ctp-multi-tools','MULTI-TOOL','PLUNGE • TRIM • REPAIR',['Tight access','Remodeling','Blade systems']),
P('tools-8','tools','Jobsite Vacuums & Dust Control','Helps control cleanup time and airborne dust during remodeling, sanding, cutting and occupied-home work.','Shop current eBay listings',true,'jobsite vacuum dust extractor HEPA contractor','ctp-dust-control','DUST CONTROL','HEPA • VAC • CLEAN WORK',['Occupied homes','Cleanup','Dust control']),
P('welding-1','welding','Welding Helmets & PPE','Welding helmets, gloves, jackets and protective gear for fabrication and repair work.','Shop current eBay listings',true,'welding helmet gloves PPE','ctp-welding-ppe','ARC PROTECTION','HELMET • GLOVES • PPE',['Protection','Comfort','Shop use']),
P('welding-2','welding','Welding & Fabrication Tools','Clamps, magnets, grinders, inspection tools and shop gear useful around welding and fabrication work.','Shop current eBay listings',true,'welding fabrication tools clamps magnets grinder','ctp-welding-tools','FABRICATION KIT','CLAMP • GRIND • FIT-UP',['Fit-up','Grinding','Fabrication']),
P('welding-3','welding','MIG, TIG & Multi-Process Welders','Compare portable and shop machines by process, input power, duty cycle and the work they are realistically built to handle.','Shop current eBay listings',true,'MIG TIG multi process welder 120V 240V','ctp-welding-machines','WELDING POWER','MIG • TIG • MULTI-PROCESS',['120/240V','Duty cycle','Process range']),
P('welding-4','welding','Plasma Cutters & Consumables','Useful for fabrication and repair work when clean material separation is faster than abrasive cutting.','Shop current eBay listings',true,'plasma cutter consumables 120V 240V','ctp-plasma-cutters','PLASMA CUT','CUT • REPAIR • FABRICATE',['Clean cutting','Consumables','Fabrication']),
P('welding-5','welding','Welding Tables, Clamps & Magnets','Better fit-up and restraint make fabrication faster and help reduce movement, distortion and rework.','Shop current eBay listings',true,'welding table clamps magnets fabrication fixture','ctp-welding-fitup','CONTROL THE FIT','TABLE • CLAMP • FIXTURE',['Fit-up','Restraint','Repeatability']),
P('welding-6','welding','Weld Inspection & Measurement Tools','Fillet gauges, bridge-cam gauges, mirrors, lights and measurement tools for fabrication quality checks.','Shop current eBay listings',true,'weld inspection gauge bridge cam fillet gauge','ctp-weld-inspection','INSPECTION KIT','GAUGE • VERIFY • MEASURE',['Fillet gauges','Bridge cam','Quality checks']),
P('garage-1','garage','Harley-Davidson Garage & Maintenance Gear','Maintenance tools, accessories, storage and garage items for Harley owners and riders.','Shop current eBay listings',true,'Harley Davidson maintenance tools garage accessories','ctp-harley','HARLEY GARAGE','MAINTAIN • RIDE • STORE',['Maintenance','Garage','Rider gear']),
P('garage-2','garage','Mechanic Hand Tool Sets','Sockets, ratchets, wrenches and mechanic tools for vehicle, motorcycle and garage repair work.','Shop current eBay listings',true,'mechanic tool set sockets ratchets wrenches','ctp-mechanic-tools','MECHANIC CORE','SOCKET • RATCHET • WRENCH',['Hand tools','Repair','Garage']),
P('garage-3','garage','Battery Chargers & Jump Packs','Portable starting power and battery maintenance can prevent downtime when trucks, cars, bikes and equipment sit.','Shop current eBay listings',true,'automotive battery charger maintainer jump pack','ctp-battery-power','STARTING POWER','CHARGE • MAINTAIN • JUMP',['Emergency power','Battery care','Portable']),
P('garage-4','garage','TPMS, Scan & Diagnostic Tools','Basic vehicle data can turn warning lights and limp-mode symptoms into a focused repair path instead of guesswork.','Shop current eBay listings',true,'OBD2 scanner TPMS diagnostic tool','ctp-vehicle-diagnostics','DIAGNOSTICS','SCAN • TPMS • DATA',['OBD2','TPMS','Troubleshooting']),
P('garage-5','garage','Motorcycle Lifts, Jacks & Stands','Stable access matters for safe motorcycle maintenance, tire work, cleaning and winter storage.','Shop current eBay listings',true,'motorcycle lift jack stand Harley','ctp-motorcycle-lifts','LIFT & SUPPORT','JACK • STAND • SERVICE',['Stable access','Maintenance','Storage']),
P('cards-1','cards','Trading Card Protection & Grading Prep','Penny sleeves, semi-rigid holders, top loaders and storage supplies for protecting cards and preparing submissions.','Shop current eBay listings',true,'trading card penny sleeves semi rigid top loaders grading','ctp-card-protection','GRADE READY','SLEEVE • RIGID • PROTECT',['Protection','Submission prep','Storage']),
P('cards-2','cards','Card Storage & Sorting Supplies','Storage boxes, dividers, binders and sorting supplies for larger sports and trading-card collections.','Shop current eBay listings',true,'trading card storage box dividers binder','ctp-card-storage','COLLECTION CONTROL','BOX • DIVIDE • ORGANIZE',['Sorting','Storage','Inventory']),
P('cards-3','cards','Card Magnifiers, Lights & Centering Tools','Simple inspection tools help identify surface, edge, corner and centering issues before grading or listing.','Shop current eBay listings',true,'trading card magnifier light centering tool grading','ctp-card-inspection','CARD INSPECTION','LIGHT • CENTER • VERIFY',['Surface check','Centering','Pre-grade']),
P('cards-4','cards','Slab Storage & Display Cases','Protect graded cards while keeping higher-value pieces organized, portable and presentable.','Shop current eBay listings',true,'graded card slab storage case display','ctp-slab-storage','SLAB PROTECTION','STORE • DISPLAY • CARRY',['Graded cards','Display','Protection']),
P('deals-1','deals','eBay Tool Deals','Search current eBay listings for tool deals, open-box items and value buys across major brands.','Browse current deals',false,'power tools deals open box','ctp-tool-deals','TOOL DEALS','OPEN BOX • VALUE • LIVE',['Current listings','Open box','Major brands']),
P('deals-2','deals','eBay Home Improvement Deals','Current listings for home repair, hardware, lawn and garden equipment at a range of price points.','Browse current deals',false,'home improvement tools lawn garden deals','ctp-home-deals','HOME DEALS','REPAIR • HARDWARE • OUTDOOR',['Current listings','Home repair','Outdoor']),
P('deals-3','deals','Open-Box & Certified Refurbished Tools','A practical search for lower-cost equipment where condition, seller history, warranty and return terms can be compared.','Browse current deals',false,'certified refurbished open box power tools','ctp-refurb-tools','REFURB VALUE','CERTIFIED • OPEN BOX • SAVE',['Lower cost','Seller history','Warranty check'])
];