const AFFILIATE_LINKS = {
  lowes: "REPLACE_WITH_LOWES_AFFILIATE_URL",
  homeDepot: "REPLACE_WITH_HOME_DEPOT_AFFILIATE_URL",
  ebay: "REPLACE_WITH_EBAY_AFFILIATE_URL",
  ace: "REPLACE_WITH_ACE_AFFILIATE_URL",
  northernTool: "REPLACE_WITH_NORTHERN_TOOL_AFFILIATE_URL"
};

const PRODUCTS = [
  {id:"tape",name:"25 ft Professional Tape Measure",category:"Contractor Tools",retailer:"Lowe's",retailerKey:"lowes",badge:"Everyday carry",note:"A contractor-grade 25-footer is one of the highest-use tools on a remodeling or framing job. Look for readable markings, solid standout, a dependable hook, and a case that survives drops.",tags:["measure","layout","framing"],featured:true},
  {id:"impact",name:"Brushless Impact Driver Kit",category:"Contractor Tools",retailer:"The Home Depot",retailerKey:"homeDepot",badge:"High-use tool",note:"For decking, framing hardware, screws, service calls, and general remodeling, a compact brushless impact earns its keep fast. Battery platform matters as much as the tool.",tags:["impact","cordless","fastening"],featured:true},
  {id:"headlamp",name:"Rechargeable Jobsite Headlamp",category:"Contractor Tools",retailer:"Ace Hardware",retailerKey:"ace",badge:"Hands-free",note:"Useful in crawlspaces, attics, service work, trailer repairs, and any job where both hands need to stay on the work.",tags:["lighting","inspection","service"],featured:false},
  {id:"helmet",name:"Auto-Darkening Welding Helmet",category:"Welding & Shop Gear",retailer:"Northern Tool",retailerKey:"northernTool",badge:"Shop essential",note:"Prioritize optical clarity, reliable arc sensing, comfortable headgear, replaceable lenses, and enough viewing area for fabrication and repair work.",tags:["welding","helmet","ppe"],featured:true},
  {id:"clamps",name:"Heavy-Duty Welding Clamp Set",category:"Welding & Shop Gear",retailer:"Northern Tool",retailerKey:"northernTool",badge:"Fabrication",note:"Good fit-up starts with control. A useful clamp mix helps hold assemblies square, close gaps, and keep parts from moving during tack-up.",tags:["clamps","fit-up","fabrication"],featured:false},
  {id:"flap",name:"40/60/80 Grit Flap Disc Assortment",category:"Welding & Shop Gear",retailer:"Lowe's",retailerKey:"lowes",badge:"Consumable",note:"An assortment covers weld blending, scale cleanup, edge prep, and finish work without forcing one grit to do every job.",tags:["grinder","abrasive","metal"],featured:false},
  {id:"lights",name:"High-Output LED Garage Lights",category:"Garage & Harley",retailer:"The Home Depot",retailerKey:"homeDepot",badge:"Garage upgrade",note:"Bright, even lighting makes maintenance, detailing, fabrication, and parts inspection easier. Compare real lumen output and coverage.",tags:["garage","lighting","harley"],featured:true},
  {id:"lift",name:"Motorcycle / ATV Lift",category:"Garage & Harley",retailer:"Northern Tool",retailerKey:"northernTool",badge:"Maintenance",note:"A stable low-profile lift can make cleaning, tire work, inspection, and maintenance easier. Verify capacity and lift-point compatibility before use.",tags:["harley","motorcycle","lift"],featured:false},
  {id:"maintainer",name:"Smart Battery Maintainer",category:"Garage & Harley",retailer:"Ace Hardware",retailerKey:"ace",badge:"Seasonal essential",note:"Cheap insurance for a motorcycle or seasonal vehicle that sits. Look for automatic maintenance mode and correct battery-chemistry support.",tags:["battery","harley","charger"],featured:false},
  {id:"sleeves",name:"Premium Trading Card Penny Sleeves",category:"Cards & Collectibles",retailer:"eBay",retailerKey:"ebay",badge:"Collection basic",note:"Clean, correctly sized sleeves are the first protection layer for raw cards before top loaders, semi-rigids, binders, shipping, or grading prep.",tags:["pokemon","sports cards","grading"],featured:true},
  {id:"semirigid",name:"Semi-Rigid Card Holders",category:"Cards & Collectibles",retailer:"eBay",retailerKey:"ebay",badge:"Grading prep",note:"Useful for grading submissions and protected storage. Pair with a fresh penny sleeve and avoid forcing cards into holders that are too tight.",tags:["cards","psa","grading"],featured:false},
  {id:"shipping",name:"Trading Card Shipping Supply Kit",category:"Cards & Collectibles",retailer:"eBay",retailerKey:"ebay",badge:"Seller setup",note:"Consistent sleeves, top loaders, team bags, cardboard protection, and mailers reduce damage risk and make online order packing faster.",tags:["ebay","shipping","cards"],featured:false},
  {id:"combo",name:"Cordless Combo Kit Deal Watch",category:"Deals",retailer:"The Home Depot",retailerKey:"homeDepot",badge:"Deal watch",note:"Combo kits can be the fastest way to enter or expand a battery platform when the included tools are ones you will actually use.",tags:["deal","combo kit","cordless"],featured:false},
  {id:"grinder",name:"Angle Grinder Deal Watch",category:"Deals",retailer:"Lowe's",retailerKey:"lowes",badge:"Deal watch",note:"A grinder crosses metalwork, masonry, cleanup, and repair. A sale is worthwhile when the tool has the power, guard setup, and wheel compatibility you need.",tags:["deal","grinder","metal"],featured:false}
];
